version: '2'
services:
    permitme-app:
        image: permitme
        external_links:
            - permitme-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/permitme
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    permitme-postgresql:
        extends:
            file: postgresql.yml
            service: permitme-postgresql
